import pickle, smtplib

from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime


def reset_data():
    dict1 = {
        "myself": 0
    }

    file = open("data/balance_sheet", "wb")
    pickle.dump(dict1, file)
    file.close()
    file = open("data/main_data", "rb")
    _data = pickle.load(file)
    file.close()
    return _data


def reset_profiles():
    dict1 = {
        "myself": ["Jym Patel", "jympatel@yahoo.com", True]
    }

    file = open("data/profiles", "wb")
    pickle.dump(dict1, file)
    file.close()


def reset_settings():
    dict1 = {
        "default_email" : "jympatel.testmail01@gmail.com",
    }

    file = open("data/settings", "wb")
    pickle.dump(dict1, file)
    file.close()


def help():
    help_doc = open("./docs/help.txt")
    print(help_doc.read())
    print("if you think help file is broken or incorrect please visit github.com/JymPatel/python")


def send_mail(user_balance ,name, reciver_email, sender_email, password):  
    print("Setting up Server ...")
    smtp = smtplib.SMTP('smtp.gmail.com', 587)
    smtp.ehlo()
    print("Starting Server ...")
    smtp.starttls()
    smtp.login(sender_email, password)
    # == create message ==
    print("Creating Mail ...")
    msg = MIMEMultipart()
    msg['Subject'] = "Balance Update"
    msg.attach(MIMEText("dear, " + name + "!\n"))
    msg.attach(MIMEText("as of now( " + str(datetime.now()) + " ), we have to pay you " + str(-1*user_balance)+ " INR\ngreetings!!"))
    msg.attach(MIMEText("\n<this mail is auto-generated by python program.>\nget program at https://github.com/JymPatel/uselesss-manager"))
    print("Sending Mail ...")
    smtp.sendmail(from_addr=sender_email,
              to_addrs=reciver_email, msg=msg.as_string())
    print("Closing Server ...")
    smtp.quit()